const config = {
  production: {
    accessTokenSecret: "NwqeSDI3WCYJBnn1YY5Yaq2,96y59rn8",
    refreshAccessTokenSecret: "truyiUIIViBubi63WPlmwaczx7f4s20l",
    expTime: "20m",
    logging: false,
    code: "INDIAPOWER",
    name: "INDIA POWER CORPORATION LIMITED",
    isin: "",
    cin: "",
    address: "Plot No.X1-2&3, Block-EP, Sector–V, Salt Lake City, Kolkata–700091",
    city: "Kolkata",
    state: "West Bengal",
    pin: "700091",
    phone: "+91 33 6609 4300",
    fax: "033 2357 2452",
    website: "https://www.indiapower.com",
    email: "rta@cbmsl.com",
    total_capital: 0,
    share_value: 0,
    meta_tag: "CB-Intrade",
    contact_person: "",
    window_close_from: "",
    window_close_to: "",
    CO: {
      pan: "NOPAN00000",
      emp_code: "000001",
      name: "Subhabrata Biswas",
      email: "subhabrata@cbmsl.co",
      designation: "Vice President",
      phone: "+91 33 6609 4300",
      address: "Plot No.X1-2&3, Block-EP, Sector–V, Salt Lake City, Kolkata–700091",
      total_share: 0,
      last_benpos_date: "",
      date_of_appointment_as_insider: "",
      last_institute: "",
      last_employer: "",
      is_compliance: true,
      is_active: true,
      status: "Active",
    },
    Management: {
      pan: "MPAN00000",
      emp_code: "",
      name: "CBMSL",
      email: "",
      designation: "",
      phone: "",
      address: "",
      total_share: 0,
      last_benpos_date: "",
      date_of_appointment_as_insider: "",
      last_institute: "",
      last_employer: "",
      is_compliance: false,
      is_active: true,
      status: "Active",
      isManagement: true,
    },
    username: "postgres",
    password: "QaTC1LAplD19ul8MciMi",
    database: "cbmslupsi",
    host: "database-1.cprdocw88mil.ap-south-1.rds.amazonaws.com",
    dialect: "postgres",
    port: "5432",
    backupLocation: "backup",
    mailId: "quicser.sender@gmail.com",
    mailPassword: "dxsoluynimtaatnv",
    backendUrl: "http://cbintrade.s3-website.ap-south-1.amazonaws.com",
    credentials: ["pan", "folio"],
    frontendUrl: "http://cbintrade-upsi.s3-website.ap-south-1.amazonaws.com",
    smtpFlag: false,
    smtpDetail: {
      service: "",
      host: "",
      secureConnection: true,
      port: "",
      tls: { rejectUnauthorized: false },
    },
  },
};

module.exports = config;
